version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: pr-dashboard-v1-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: pr-dashboard-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build dashboard
          command: |
            npm run production
      - run:
          name: Publish on Github Pages
          command: |
            npm run publish
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  master-workflow:
    jobs:
      - publish:
          filters:
            branches:
              only: master
